# .gitlab-ci.yml

stages:
  - build
  - test

image: docker:20.10.16

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:20.10.16-dind


build:
  stage: build
  tags: 
    - runner
  before_script:
    - docker version
  script:
    - docker info
    - docker login registry.gitlab.com -u GurlovleenSingh -p Ansibleaws123**
    - docker build -t registry.gitlab.com/project1740/ngnix_project:$CI_PIPELINE_IID .
    - docker push registry.gitlab.com/project1740/ngnix_project:$CI_PIPELINE_IID
  artifacts:
    paths:
      - $CI_PROJECT_DIR/
    exclude:
      - Dockerfile

test_job:
  stage: test
  tags:
    - runner
  script:
    - docker login registry.gitlab.com -u GurlovleenSingh -p Ansibleaws123** 
    - docker pull registry.gitlab.com/project1740/ngnix_project:$CI_PIPELINE_IID
    - docker image ls
    


