# .gitlab-ci.yml

stages:
  - build

image: docker:20.10.16

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:20.10.16-dind


build:
  stage: build
  tags: 
    - runner
  before_script:
    - docker version
  script:
    - docker info
    - docker login registry.gitlab.com -u GurlovleenSingh -p $TOKEN
    - docker build -t registry.gitlab.com/project1740/ngnix_project .
    - docker push registry.gitlab.com/project1740/ngnix_project

